name: Update plugin store

on:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check plugin updates
        run: make plugins
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Bot] Update plugin store manifests"
          commit-message: "[Bot] Update plugin store manifests"
          branch: update-plugin-store
          add-paths: store-plugin.json
          reviewers: qianlifeng
