name: Update plugin store

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3
      - name: Check plugin updates
        run: make plugins
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Bot] Update plugin store manifests"
          commit-message: "[Bot] Update plugin store manifests"
          branch: update-plugin-store
          add-paths: store-plugin.json
          reviewers: qianlifeng
